import localFont from "next/font/local";
import "./globals.css";
import Tanstack from "@/Services/Tanstack";
import AuthProvider from "@/Services/AuthProvider";
import { Raleway } from "next/font/google";
import Script from "next/script";

const raleway = Raleway({
  subsets: ["latin"], // Latin subset for better performance
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // All font weights
  style: ["normal", "italic"], // Normal and italic styles
});

export const metadata = {
  title: "Zinnodev | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${raleway.className}  antialiased`}>
        <Tanstack>
          <AuthProvider>{children}</AuthProvider>
        </Tanstack>
      </body>
    </html>
  );
}
